sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t terhje/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true terhje/react-test npm test 

after_success:
  - docker build -t terhje/multi-client ./client
  - docker build -t terhje/multi-nginx ./nginx
  - docker build -t terhje/multi-server ./server
  - docker build -t terhje/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push terhje/multi-client
  - docker push terhje/multi-nginx
  - docker push terhje/multi-server
  - docker push terhje/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-022575196026'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY